apiVersion: v1
kind: Service
metadata:
  name: hydradx-service
spec:
  selector:
    app: node
  type: NodePort
  ports:
    - protocol: TCP
      port: 30333
      targetPort: 30333
      nodePort: 30333
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hydradx-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  serviceName: "hydradx-node"
  template:
    metadata:
      labels:
        app: node
      annotations:
        prometheus.io/scrape: 'false'
        prometheus.io/port: '9615'
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: node
        image: gvonbergen/hydradx-node:5.0.0
        command: ["/usr/local/bin/hydra-dx"]
        args:
        - "--chain"
        - "lerna"
        - "--name"
        - "SwissHydra"
        - "--validator"
        ports:
        - containerPort: 30333
        volumeMounts:
        - name: database-volume
          mountPath: "/data"
  volumeClaimTemplates:
  - metadata:
      name: database-volume
    spec:
      storageClassName: scw-bssd-retain
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi