[package]
name = "hydra-dx-build-script-utils"
version = "1.0.0"
description = "Crate with utility functions for `build.rs` scripts."
authors = ["GalacticCouncil <hydradx@galacticcouncil.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
platforms = "1.1"
cargo-lock = "4.0"
