[package]
authors = ['GalacticCouncil']
description = 'HydraDX Transaction Payment Benchmarking Module'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydra-dx'
license = 'Apache 2.0'
name = 'pallet-multi-payment-benchmarking'
repository = 'https://github.com/galacticcouncil/hydra-dx'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = {package = 'substrate-wasm-builder', version = '3.0.0'}

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
serde = {features = ['derive'], optional = true, version = '1.0.101'}

# Local dependencies
pallet-amm = {path = '../../amm', default-features = false}
pallet-asset-registry = {path = '../../asset-registry', default-features = false}
pallet-balances = {path = '../../balances', default-features = false}
pallet-transaction-multi-payment = {path = '../../transaction-multi-payment', default-features = false}
primitives = {path = '../../../primitives', default-features = false}

# ORML dependencies
orml-currencies = {default-features = false, version = "0.4.1-dev"}
orml-tokens = {default-features = false, version = "0.4.1-dev"}
orml-traits = {default-features = false, version = "0.4.1-dev"}
orml-utilities = {default-features = false, version = "0.4.1-dev"}

# Substrate dependencies
frame-benchmarking = {default-features = false, version = '3.0.0'}
frame-support = {default-features = false, version = '3.0.0'}
frame-system = {default-features = false, version = '3.0.0'}
frame-system-benchmarking = {default-features = false, version = '3.0.0'}

pallet-transaction-payment = {default-features = false, version = '3.0.0'}
sp-std = {default-features = false, version = '3.0.0'}

sp-core = {default-features = false, version = '3.0.0'}
sp-runtime = {default-features = false, version = '3.0.0'}

[dev-dependencies]
sp-io = {default-features = false, version = '3.0.0'}

[features]
default = ['std']
std = [
  'serde',
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'sp-std/std',
  'sp-runtime/std',
  'primitives/std',
  'pallet-amm/std',
  'pallet-asset-registry/std',
  'pallet-transaction-multi-payment/std',
  "frame-benchmarking/std",
]
