[package]
authors = ['GalacticCoucil']
description = 'Transaction multi currency payment support module'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydra-dx'
license = 'Apache 2.0'
name = 'pallet-transaction-multi-payment'
repository = 'https://github.com/galacticcouncil/hydra-dx'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = {package = 'substrate-wasm-builder', version = '3.0.0'}

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
primitive-types = {default-features = false, version = '0.8.0'}
serde = {features = ['derive'], optional = true, version = '1.0.101'}

# Local dependecies
pallet-amm = {path = '../amm', default-features = false}
pallet-asset-registry = {path = '../asset-registry', default-features = false}
primitives = {path = '../../primitives', default-features = false}

# ORML dependencies
orml-tokens = {default-features = false, version = "0.4.1-dev"}
orml-traits = {default-features = false, version = "0.4.1-dev"}
orml-utilities = {default-features = false, version = "0.4.1-dev"}

# Substrate dependencies
frame-support = {default-features = false, version = '3.0.0'}
frame-system = {default-features = false, version = '3.0.0'}
sp-api = {default-features = false, version = '3.0.0'}
sp-core = {default-features = false, version = '3.0.0'}
sp-runtime = {default-features = false, version = '3.0.0'}
sp-std = {default-features = false, version = '3.0.0'}

pallet-balances = {path = '../balances', default-features = false, version = '3.0.0'}
pallet-transaction-payment = {default-features = false, version = '3.0.0'}

[dev-dependencies]
orml-currencies = {default-features = false, version = "0.4.1-dev"}
pallet-transaction-payment = {default-features = false, version = '3.0.0'}
sp-io = {default-features = false, version = '3.0.0'}

[features]
default = ['std']
std = [
  'serde/std',
  'codec/std',
  'sp-core/std',
  'sp-api/std',
  'frame-support/std',
  'frame-system/std',
  'sp-runtime/std',
  'orml-tokens/std',
  'orml-traits/std',
  'pallet-balances/std',
  'pallet-asset-registry/std',
  'pallet-amm/std',
]
